/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9dd4b2c45cad27ab1aff28c300243170)
interface __BaseEnv_Env {
	LEGACY_DATA: KVNamespace;
	DB: D1Database;
	LOGIN_RATE_LIMITER: RateLimit;
	EXPORT_RATE_LIMITER: RateLimit;
	IMPORT_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface DevelopmentEnv {
		LEGACY_DATA: KVNamespace;
		DB: D1Database;
		LOGIN_RATE_LIMITER: RateLimit;
		EXPORT_RATE_LIMITER: RateLimit;
		IMPORT_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
	interface StagingEnv {
		LEGACY_DATA: KVNamespace;
		DB: D1Database;
		LOGIN_RATE_LIMITER: RateLimit;
		EXPORT_RATE_LIMITER: RateLimit;
		IMPORT_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
