/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b32bc6bde2464be1dc4667b82262940f)
interface __BaseEnv_Env {
	DB: D1Database;
	LOGIN_RATE_LIMITER: RateLimit;
	EXPORT_RATE_LIMITER: RateLimit;
	IMPORT_RATE_LIMITER: RateLimit;
	LIVE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface DevelopmentEnv {
		DB: D1Database;
		LOGIN_RATE_LIMITER: RateLimit;
		EXPORT_RATE_LIMITER: RateLimit;
		IMPORT_RATE_LIMITER: RateLimit;
		LIVE_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
	interface StagingEnv {
		DB: D1Database;
		LOGIN_RATE_LIMITER: RateLimit;
		EXPORT_RATE_LIMITER: RateLimit;
		IMPORT_RATE_LIMITER: RateLimit;
		LIVE_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
