/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cd30c0b0ac25c9fb242e65bed9fb444c)
interface __BaseEnv_Env {
	LEGACY_DATA: KVNamespace;
	DB: D1Database;
	LOGIN_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	TEST_MIGRATIONS?: Array<{ name: string; queries: string[] }>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface DevelopmentEnv {
		LEGACY_DATA: KVNamespace;
		DB: D1Database;
		LOGIN_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
	interface StagingEnv {
		LEGACY_DATA: KVNamespace;
		DB: D1Database;
		LOGIN_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
